#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u https://github.com/ShapeShiftOS/android_manifest.git -b android_11 -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 10

git clone https://github.com/neel685/device_xiaomi_sdm845-common device/xiaomi/sdm845-common -b ssos --depth=1
git clone https://github.com/neel685/device_xiaomi_beryllium device/xiaomi/beryllium -b ssos --depth=1
git clone https://github.com/LineageOS/android_kernel_xiaomi_sdm845 kernel/xiaomi/sdm845 --depth=1
git clone https://gitlab.com/the-muppets/proprietary_vendor_xiaomi vendor/xiaomi --depth=1
git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi --depth=1 

